version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: runstrong_db
      POSTGRES_USER: runstrong
      POSTGRES_PASSWORD: runstrong_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U runstrong -d runstrong_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: